/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quickpasstesis.igu;

import com.mycompany.quickpasstesis.logica.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PantallaPrincipalForm extends javax.swing.JFrame {
    private Usuario usuarioSesion;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipalForm(Usuario usuarioSesion) {
        initComponents();
        this.usuarioSesion = usuarioSesion;
        
        if (usuarioSesion.getTipoRol() != Usuario.TipoRol.ADMINISTRADOR){
        btnRegistroUsuario.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPPrincipl = new javax.swing.JPanel();
        jLabelPPrincipal = new javax.swing.JLabel();
        jPanelBtn = new javax.swing.JPanel();
        bntModuloINV = new javax.swing.JButton();
        btnRegistroUsuario = new javax.swing.JButton();
        bntConsultasReportes = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        jpanelCeleste = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPPrincipl.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPPrincipl.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabelPPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabelPPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPPrincipal.setText("Pantalla Principal");

        jPanelBtn.setBackground(new java.awt.Color(255, 255, 255));

        bntModuloINV.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        bntModuloINV.setText("Módulo Inventario");
        bntModuloINV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntModuloINV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModuloINVActionPerformed(evt);
            }
        });

        btnRegistroUsuario.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        btnRegistroUsuario.setText("Registro Usuario");
        btnRegistroUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsuarioActionPerformed(evt);
            }
        });

        bntConsultasReportes.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        bntConsultasReportes.setText("Consultas y Reportes");
        bntConsultasReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntConsultasReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConsultasReportesActionPerformed(evt);
            }
        });

        btnRegistro.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        btnRegistro.setText("Registro QuickPass");
        btnRegistro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnMantenimiento.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        btnMantenimiento.setText("Mantenimiento");
        btnMantenimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnLayout = new javax.swing.GroupLayout(jPanelBtn);
        jPanelBtn.setLayout(jPanelBtnLayout);
        jPanelBtnLayout.setHorizontalGroup(
            jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntConsultasReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntModuloINV, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanelBtnLayout.setVerticalGroup(
            jPanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bntModuloINV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntConsultasReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPPrinciplLayout = new javax.swing.GroupLayout(jPanelPPrincipl);
        jPanelPPrincipl.setLayout(jPanelPPrinciplLayout);
        jPanelPPrinciplLayout.setHorizontalGroup(
            jPanelPPrinciplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPPrinciplLayout.createSequentialGroup()
                .addComponent(jPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(jPanelPPrinciplLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabelPPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPPrinciplLayout.setVerticalGroup(
            jPanelPPrinciplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPPrinciplLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelPPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpanelCeleste.setBackground(new java.awt.Color(102, 153, 255));
        jpanelCeleste.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\file (5).png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jpanelCelesteLayout = new javax.swing.GroupLayout(jpanelCeleste);
        jpanelCeleste.setLayout(jpanelCelesteLayout);
        jpanelCelesteLayout.setHorizontalGroup(
            jpanelCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelCelesteLayout.createSequentialGroup()
                .addGap(0, 249, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpanelCelesteLayout.setVerticalGroup(
            jpanelCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCelesteLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPPrincipl, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelCeleste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPPrincipl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntModuloINVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModuloINVActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            ModuloInventarioForm moduloInventarioForm = new ModuloInventarioForm();
            moduloInventarioForm.setLocationRelativeTo(null); // Centra la ventana
            moduloInventarioForm.setVisible(true); // Muestra el formulario
        }
    });
    }//GEN-LAST:event_bntModuloINVActionPerformed

    private void btnRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsuarioActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            
            Usuario usuarioSesion = obternerUsuarioenSesion();
            // Verifica si el usuario en sesión es válido
            if (usuarioSesion == null) {
                JOptionPane.showMessageDialog(null, "Debes iniciar sesión para acceder a esta función.");
                return;
            }

            // Pasa el usuario en sesión al constructor de RegistroUsuariosForm
            RegistroUsuariosForm registroUsuariosForm = new RegistroUsuariosForm(usuarioSesion);
            registroUsuariosForm.setLocationRelativeTo(null); // Centra la ventana
            registroUsuariosForm.setVisible(true); // Muestra el formulario
        }
    });
    }//GEN-LAST:event_btnRegistroUsuarioActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cerrar sesión?", 
            "Confirmar Cierre de Sesión", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
        
            if (opcion == JOptionPane.YES_OPTION){
            this.dispose();
            }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void bntConsultasReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConsultasReportesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            ConsultaReporteForm consultaReporteForm = new ConsultaReporteForm();
            consultaReporteForm.setLocationRelativeTo(null); // Centra la ventana
            consultaReporteForm.setVisible(true); // Muestra el formulario
        }
    });
    }//GEN-LAST:event_bntConsultasReportesActionPerformed

    private Usuario obternerUsuarioenSesion (){
    
    return this.usuarioSesion;
    }
    public void setUsuarioSesion(Usuario usuarioSesion) {
        this.usuarioSesion = usuarioSesion;
    }
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConsultasReportes;
    private javax.swing.JButton bntModuloINV;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnRegistroUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPPrincipal;
    private javax.swing.JPanel jPanelBtn;
    private javax.swing.JPanel jPanelPPrincipl;
    private javax.swing.JPanel jpanelCeleste;
    // End of variables declaration//GEN-END:variables
}
